-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 17:17:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`titles` ;

CREATE TABLE IF NOT EXISTS `db`.`titles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`roles` ;

CREATE TABLE IF NOT EXISTS `db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`users` ;

CREATE TABLE IF NOT EXISTS `db`.`users` (
  `user_id` VARCHAR(36) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(500) NOT NULL,
  `register_at` DATETIME NOT NULL,
  `gender` ENUM("male", "female", "other") NOT NULL,
  `phone_number` VARCHAR(12) NOT NULL,
  `banned` TINYINT NOT NULL,
  `intro` TINYTEXT NOT NULL,
  `image` VARCHAR(500) NOT NULL,
  `birth_date` DATETIME NOT NULL,
  `balance` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `title` INT NOT NULL,
  `role` INT NOT NULL,
  `avg_rating` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `fk_users_titles_idx` (`title` ASC) VISIBLE,
  INDEX `fk_users_roles1_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `fk_users_titles`
    FOREIGN KEY (`title`)
    REFERENCES `db`.`titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`role`)
    REFERENCES `db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`payment_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`payment_type` ;

CREATE TABLE IF NOT EXISTS `db`.`payment_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`payments` ;

CREATE TABLE IF NOT EXISTS `db`.`payments` (
  `payment_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  `payment_description` TINYTEXT NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `type` INT NOT NULL,
  `state` ENUM("pending", "cancelled", "done") NOT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`payment_id` ASC) VISIBLE,
  INDEX `fk_payments_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_payments_payment_type1_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `fk_payments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payments_payment_type1`
    FOREIGN KEY (`type`)
    REFERENCES `db`.`payment_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`manual_payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`manual_payments` ;

CREATE TABLE IF NOT EXISTS `db`.`manual_payments` (
  `payment_id` VARCHAR(36) NOT NULL,
  `creator_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  `manual_paymentscol` VARCHAR(45) NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_manual_payments_users1_idx` (`creator_id` ASC) VISIBLE,
  CONSTRAINT `fk_manual_payments_payments1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `db`.`payments` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_manual_payments_users1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`vnpay_payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`vnpay_payments` ;

CREATE TABLE IF NOT EXISTS `db`.`vnpay_payments` (
  `vnp_trans_no` VARCHAR(45) NOT NULL,
  `payment_id` VARCHAR(36) NOT NULL,
  `vnp_order_info` TINYTEXT NOT NULL,
  `vnp_amount` DECIMAL(15,2) NOT NULL,
  `vnp_back_code` VARCHAR(45) NOT NULL,
  `vnp_bank_tran_no` VARCHAR(45) NOT NULL,
  `vnp_card_type` VARCHAR(45) NOT NULL,
  `vnp_date` DATETIME NOT NULL,
  PRIMARY KEY (`vnp_trans_no`, `payment_id`),
  CONSTRAINT `fk_vnpay_payments_payments1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `db`.`payments` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`administrative_regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`administrative_regions` ;

CREATE TABLE IF NOT EXISTS `db`.`administrative_regions` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NOT NULL,
  `code_name` VARCHAR(255) NULL,
  `code_name_en` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`administrative_units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`administrative_units` ;

CREATE TABLE IF NOT EXISTS `db`.`administrative_units` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(255) NULL,
  `full_name_en` VARCHAR(255) NULL,
  `short_name` VARCHAR(255) NULL,
  `short_name_en` VARCHAR(255) NULL,
  `code_name` VARCHAR(255) NULL,
  `code_name_en` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`provinces` ;

CREATE TABLE IF NOT EXISTS `db`.`provinces` (
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `name_en` VARCHAR(255) NULL,
  `full_name` VARCHAR(255) NULL,
  `full_name_en` VARCHAR(255) NULL,
  `code_name` VARCHAR(255) NULL,
  `administrative_region_id` INT NOT NULL,
  `administrative_unit_id` INT NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_provinces_administrative_regions1_idx` (`administrative_region_id` ASC) VISIBLE,
  INDEX `fk_provinces_administrative_units1_idx` (`administrative_unit_id` ASC) VISIBLE,
  CONSTRAINT `fk_provinces_administrative_regions1`
    FOREIGN KEY (`administrative_region_id`)
    REFERENCES `db`.`administrative_regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_provinces_administrative_units1`
    FOREIGN KEY (`administrative_unit_id`)
    REFERENCES `db`.`administrative_units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`districts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`districts` ;

CREATE TABLE IF NOT EXISTS `db`.`districts` (
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(255) NULL,
  `name_en` VARCHAR(255) NULL,
  `full_name` VARCHAR(255) NULL,
  `full_name_en` VARCHAR(255) NULL,
  `code_name` VARCHAR(255) NULL,
  `province_code` VARCHAR(20) NOT NULL,
  `administrative_unit_id` INT NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_districts_provinces1_idx` (`province_code` ASC) VISIBLE,
  INDEX `fk_districts_administrative_units1_idx` (`administrative_unit_id` ASC) VISIBLE,
  CONSTRAINT `fk_districts_provinces1`
    FOREIGN KEY (`province_code`)
    REFERENCES `db`.`provinces` (`code`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_districts_administrative_units1`
    FOREIGN KEY (`administrative_unit_id`)
    REFERENCES `db`.`administrative_units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`wards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`wards` ;

CREATE TABLE IF NOT EXISTS `db`.`wards` (
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(255) NULL,
  `name_en` VARCHAR(255) NULL,
  `full_name` VARCHAR(255) NULL,
  `full_name_en` VARCHAR(255) NULL,
  `code_name` VARCHAR(255) NULL,
  `district_code` VARCHAR(20) NOT NULL,
  `administrative_unit_id` INT NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_wards_districts1_idx` (`district_code` ASC) VISIBLE,
  INDEX `fk_wards_administrative_units1_idx` (`administrative_unit_id` ASC) VISIBLE,
  CONSTRAINT `fk_wards_districts1`
    FOREIGN KEY (`district_code`)
    REFERENCES `db`.`districts` (`code`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_wards_administrative_units1`
    FOREIGN KEY (`administrative_unit_id`)
    REFERENCES `db`.`administrative_units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`house_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`house_types` ;

CREATE TABLE IF NOT EXISTS `db`.`house_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`houses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`houses` ;

CREATE TABLE IF NOT EXISTS `db`.`houses` (
  `house_id` INT NOT NULL AUTO_INCREMENT,
  `owner_id` VARCHAR(36) NOT NULL,
  `latitude` DECIMAL(9,6) NOT NULL,
  `longtitude` DECIMAL(9,6) NOT NULL,
  `address` VARCHAR(500) NOT NULL,
  `provinces_code` VARCHAR(20) NOT NULL,
  `districts_code` VARCHAR(20) NOT NULL,
  `wards_code` VARCHAR(20) NOT NULL,
  `price` DECIMAL(15,2) NOT NULL,
  `thumbnail` VARCHAR(2048) NOT NULL,
  `title` VARCHAR(2048) NOT NULL,
  `house_type` INT NOT NULL,
  `video` VARCHAR(2048) NULL,
  `visible` TINYINT NOT NULL,
  `square` DECIMAL(10,2) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `description` TEXT NOT NULL,
  `A/C` TINYINT NULL,
  `parking` TINYINT NULL,
  `whole_house` TINYINT NULL,
  `pet` TINYINT NULL,
  `elevator` TINYINT NULL,
  `rooms` INT NULL,
  `bath_rooms` INT NULL,
  `bedrooms` INT NULL,
  `maintainance_fee` DECIMAL(15,2) NULL,
  PRIMARY KEY (`house_id`, `owner_id`),
  INDEX `fk_houses_provinces1_idx` (`provinces_code` ASC) VISIBLE,
  INDEX `fk_houses_districts1_idx` (`districts_code` ASC) VISIBLE,
  INDEX `fk_houses_wards1_idx` (`wards_code` ASC) VISIBLE,
  INDEX `fk_houses_house_types1_idx` (`house_type` ASC) VISIBLE,
  INDEX `fk_houses_users1_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_houses_provinces1`
    FOREIGN KEY (`provinces_code`)
    REFERENCES `db`.`provinces` (`code`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_houses_districts1`
    FOREIGN KEY (`districts_code`)
    REFERENCES `db`.`districts` (`code`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_houses_wards1`
    FOREIGN KEY (`wards_code`)
    REFERENCES `db`.`wards` (`code`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_houses_house_types1`
    FOREIGN KEY (`house_type`)
    REFERENCES `db`.`house_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_houses_users1`
    FOREIGN KEY (`owner_id`)
    REFERENCES `db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`house_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`house_images` ;

CREATE TABLE IF NOT EXISTS `db`.`house_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(2048) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`house_has_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`house_has_images` ;

CREATE TABLE IF NOT EXISTS `db`.`house_has_images` (
  `houses_id` INT NOT NULL,
  `house_images_id` INT NOT NULL,
  PRIMARY KEY (`houses_id`, `house_images_id`),
  INDEX `fk_houses_has_house_images_house_images1_idx` (`house_images_id` ASC) VISIBLE,
  INDEX `fk_houses_has_house_images_houses1_idx` (`houses_id` ASC) VISIBLE,
  CONSTRAINT `fk_houses_has_house_images_houses1`
    FOREIGN KEY (`houses_id`)
    REFERENCES `db`.`houses` (`house_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_houses_has_house_images_house_images1`
    FOREIGN KEY (`house_images_id`)
    REFERENCES `db`.`house_images` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`orders` ;

CREATE TABLE IF NOT EXISTS `db`.`orders` (
  `order_id` INT NOT NULL,
  `house_id` INT NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME NULL,
  `total` DECIMAL(15,2) NULL,
  PRIMARY KEY (`order_id`, `house_id`),
  INDEX `fk_orders_houses1_idx` (`house_id` ASC) VISIBLE,
  INDEX `fk_orders_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_houses1`
    FOREIGN KEY (`house_id`)
    REFERENCES `db`.`houses` (`house_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db`.`rating` ;

CREATE TABLE IF NOT EXISTS `db`.`rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rating_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_rating_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `db`;

DELIMITER $$

USE `db`$$
DROP TRIGGER IF EXISTS `db`.`rating_AFTER_INSERT` $$
USE `db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `db`.`rating_AFTER_INSERT` AFTER INSERT ON `rating` FOR EACH ROW
BEGIN
	DECLARE avg_rating_variable float;
    SET @avg_rating_variable := (SELECT ROUND(avg(rating), 2) FROM `rating` WHERE user_id = NEW.user_id);
    UPDATE users 
	SET 
		avg_rating = avg_rating_variable
	WHERE
		user_id = NEW.user_id;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
